### ISSUE TITLE
Incompatible with PHP 8.1

### ISSUE THREAD

**Issue by jesperingels** [svalveson/SliderOptions#4]
Hi,

Thx for creating this module!
Could you set the PHP version to `^7.0 || ^8.0` in composer.json? 

My project is using PHP 8.1, so I can't install this module with composer without php version errors.
As this project contains almost no PHP it wouldn't be a problem right?

**Comment by svalveson** [comment]
Yes, for sure. I need the same so i'll approve the PR.
Thanks!

**Comment by barryvdh** [comment]
Can you tag a new release with this?

**Comment by svalveson** [comment]
@barryvdh check this out [v1.0.1](https://github.com/svalveson/SliderOptions/releases/tag/v1.0.1)

**Comment by barryvdh** [comment]
Very nice, thanks
